# Generated by Django 5.2.1 on 2025-05-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата обновления')),
                ('company_name', models.CharField(max_length=255, verbose_name='наименование компании')),
                ('bin', models.CharField(max_length=255, verbose_name='БИН')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='статус')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='дата выдачи')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='срок действия')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
                'ordering': ['-created_at'],
            },
        ),
    ]
